### ISSUE TITLE
change required 

### ISSUE THREAD

**Issue by iftikhar2424** [shinhwagk/oracle_exporter#1]
hi
i have run your latest release its a good project and really appreciated your work but i think this will take too much load on db when it hits every time to run queries at the back end of database. how can we exclude the queries that are irrelevant and can take too much load on database.
please make your exporter release in the way that it read some file where we add desired sql queries.

thanks

**Comment by shinhwagk** [comment]
Collectors are enabled by providing a --collector.<name> flag. Collectors that are enabled by default can be disabled by providing a --no-collector.<name> flag.

**Comment by iftikhar2424** [comment]
For example i don't want to load tablespace or segments information in prometheus
instead i need to look into fast recovery area or any other dba_views how can i tackle this with your exporter.

**Comment by shinhwagk** [comment]
reference: https://github.com/prometheus/mysqld_exporter#filtering-enabled-collectors
```yml
params:
  collect[]:
  - systemEvent-11g
  - sql-11g
```
